spring:
  profiles:
    active: test
---
server:
  port: 6001
spring:
  profiles: dev
  # application:
  #   name: config-client-dev-6001


---
server:
  port: 6002
spring:
  profiles: test
  # application:
  #   name: config-client-test-6002

# eureka:
#   instance:
#     instance-id: config-client-test-6002
#   client:
#     service-url:
#       defaultZone: http://eureka7001.com
